name: Cleanup
description: 'Runs all the cleanup tasks to cleanup resources deployed during E2E'
inputs:
  account_id:
    description: "Account ID to access AWS"
    required: true
  role:
    description: "Role to access AWS"
    required: true
  region:
    description: "Region to access AWS"
    required: true
  cluster_name:
    description: 'Name of the cluster to be launched by eksctl'
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out. Requires a corresponding Karpenter snapshot release"
runs:
  using: "composite"
  steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role }}
        aws-region: ${{ inputs.region }}
        role-duration-seconds: 21600
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.git_ref }}
    - uses: actions/setup-go@v4
      with:
        go-version-file: test/hack/cleanup/go.mod
        check-latest: true
        cache-dependency-path: "test/hack/cleanup/go.sum"
    - run: |
        go run main.go ${{ inputs.cluster_name }}
      working-directory: ./test/hack/cleanup
      name: "Run cleanup script"