prometheusOperator:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  admissionWebhooks:
    patch:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
prometheus-node-exporter:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
nodeExporter:
  enabled: false
kube-state-metrics:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
grafana:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
alertmanager:
  alertmanagerSpec:
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
extraScrapeConfigs: |
    - job_name: karpenter
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - karpenter
      relabel_configs:
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: http-metrics
        action: keep
