name: E2ESoakTrigger
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  statuses: write
jobs:
  soak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/${{ vars.ROLE_NAME }}
          aws-region: us-west-2
          role-duration-seconds: 21600
      # - name: run the Soak test suite
      #   run: |
      #     aws eks update-kubeconfig --name Soak-testing 
      # - name: install karpenter
      #   uses: ./.github/actions/e2e/install-karpenter
      #   with:
      #     account_id: ${{ vars.ACCOUNT_ID }}
      #     role: ${{ vars.ROLE_NAME }}
      #     region: us-west-2
      #     cluster_name: Soak-testing
      #     git_ref: ${{ inputs.git_ref }}
      - name: run the Soak test suite
        run: |
          aws eks update-kubeconfig --name Soak-testing 
          TEST_SUITE="Soak" make e2etests