name: E2ESoakTrigger
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:       
  soak:
    needs: [resolve-cluster]
    if: github.repository == 'aws/karpenter' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/e2e-soak.yaml
    with:
      event_name: ${{ github.event_name }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}