name: E2ESoakTrigger
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_run:
    workflows: [ApprovalComment]
    types: [completed]
  workflow_dispatch:
    inputs:
      region:
        required: true
        default: 'us-west-2'
        type: choice
        options:
          - "us-east-1"
          - "us-west-2"
      cleanup:
        required: true
        default: true
        type: boolean
jobs:
  reslove_cluster:
    runs-on: ubuntu-latest
    outputs:
      CREATE_CLUSTER: ${{ steps.create_cluster.outputs.SHOULD_RUN }}
      PREEXISTING: ${{ steps.create_cluster.outputs.GIT_REF }}
    steps:
        - id: create_cluster
          run: |
            export PREEXISTING=$(eksctl get cluster -o json | jq '.[].Name' | grep soak)
            echo "Found existing cluster name \"$PREEXISTING\""
            if [[ $PREEXISTING != "" ]]; then 
                echo PREEXISTING=$PREEXISTING >> $GITHUB_OUTPUT
                echo CREATE_CLUSTER=true >> $GITHUB_OUTPUT
            else
                echo CREATE_CLUSTER=false >> $GITHUB_OUTPUT
            fi
  sock:
    needs: [reslove_cluster]
    strategy:
      fail-fast: false
      matrix:
        suite:
        - Beta/Integration
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: ${{ matrix.suite }}
      region: ${{ inputs.region || 'us-west-1' }}
      workflow_trigger: "soak"
      create_cluster: ${{needs.reslove_cluster.outputs.CREATE_CLUSTER }}
      preexisiting_cluster: ${{needs.reslove_cluster.outputs.PREEXISTING || '' }}
      # Default to true unless using a workflow_dispatch
      cleanup: false
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
