name: E2ESoakTrigger
on:
  workflow_dispatch:
jobs:
  scale:
    if: github.repository == 'aws/karpenter' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: Soak
      event_name: ${{ github.event_name }}
      region: "us-west-2"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}