name: E2ESoakTrigger
on:
  workflow_dispatch:
    inputs:
      git_ref:
        type: string
      suite:
        default: Soak
      k8s_version:
        default: "1.27"
      enable_cloudwatch:
        type: boolean
        default: false
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  statuses: write
jobs:
  soak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_ref }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/eksctl-aengeda-karpenter-workbench-us-ServiceRole-YAKOEFU9ZEZA
          aws-region: us-west-2
          role-duration-seconds: 21600
      # - name: install prometheus
      #   uses: ./.github/actions/e2e/install-prometheus
      #   with:
      #     account_id: ${{ vars.ACCOUNT_ID }}
      #     role: ${{ vars.ROLE_NAME }}
      #     region: ${{ vars.AWS_REGION }}
      #     cluster_name: ${{ env.CLUSTER_NAME }}
      #     workspace_id: ${{ vars.WORKSPACE_ID }}
      #     git_ref: ${{ inputs.git_ref }}
      - name: install karpenter
        uses: ./.github/actions/e2e/install-karpenter
        with:
          account_id: ${{ vars.ACCOUNT_ID }}
          role: ${{ vars.ROLE_NAME }}
          region: ${{ vars.AWS_REGION }}
          cluster_name: ${{ env.CLUSTER_NAME }}
          git_ref: ${{ inputs.git_ref }}
      - name: run the ${{ inputs.suite }} test suite
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }}
          TEST_SUITE="${{ inputs.suite }}" ENABLE_CLOUDWATCH=${{ inputs.enable_cloudwatch }} GIT_REF="$(git rev-parse HEAD)" make e2etestsß