name: E2ESoakTrigger
on:
  workflow_dispatch:
    inputs:
      git_ref:
        type: string
      suite:
        default: Soak
      k8s_version:
        default: "1.27"
      enable_cloudwatch:
        type: boolean
        default: false
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  statuses: write
jobs:
  soak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_ref }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/${{ vars.ROLE_NAME }}
          aws-region: us-west-2
          role-duration-seconds: 21600
      - name: run the ${{ inputs.suite }} test suite
        run: |
          aws eks update-kubeconfig --name Soak-testing 
          TEST_SUITE="${{ inputs.suite }}" make e2etests